services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: franchise_api
    restart: unless-stopped
    environment:
      PORT: 8080
      R2DBC_URL: ${R2DBC_URL}
      R2DBC_PASSWORD: ${R2DBC_PASSWORD}
    ports:
      - "8080:8080"