spring.application.name=franchise_api

# --- MySQL Azure (R2DBC) ---
spring.r2dbc.url=r2dbc:pool:mysql://academysystemdb.mysql.database.azure.com:3306/franchisedb?sslMode=REQUIRED
spring.r2dbc.username=useradmin
spring.r2dbc.password=$2a$14$qhYFxzyFtxdJ3IrHMEI9tuNTZt0WR7eJkYooEsnEoL2yPvK6AWN

# R2DBC no crea esquema automaticamente
spring.sql.init.mode=never

